# https://docs.readthedocs.io/en/stable/config-file/v2.html
---
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  jobs:
    pre_build:
      - pip install .

sphinx:
  configuration: docs/conf.py

formats:
  - pdf

python:
  install:
    - requirements: docs/requirements.txt
